### ISSUE TITLE
Error when multiple graphql operations are available

### ISSUE THREAD

**Issue by sondrele** [enonic/app-graphiql#19]
Hi. I'm testing out the [headless-starter](https://developer.enonic.com/guides/headless-starter) project to evaluate whether or not enonic is a viable cms for our projects. Related to this, I encountered an error in this app and thought I'd report it.

When executing a query, it errors when there are multiple graphql operations available.

This is the input query:
```gql
query One {
  guillotine {
    query(query: "ngram('_allText', 'morgan') AND type='com.enonic.starter.headless:person'", first: 6) {
      displayName
      ... on com_enonic_starter_headless_Person {
    	  displayName
        data {
          photos(first:1){
            ... on media_Image {
              imageUrl(type:absolute scale:"block(400,400)")
            }

          }
        }
      }
    }
  }
}

query Two {
  guillotine  {
    getChildren(key:"/hmdb/persons" first:5){
      displayName
      _path
    }  
  }
}
```

And this is the request payload. As can bee seen by `"operationName": "Two"`, I've tried to execute the second query:
```json
{
  "query": "query One {\n  guillotine {\n    query(query: \"ngram('_allText', 'morgan') AND type='com.enonic.starter.headless:person'\", first: 6) {\n      displayName\n      ... on com_enonic_starter_headless_Person {\n    \t  displayName\n        data {\n          photos(first:1){\n            ... on media_Image {\n              imageUrl(type:absolute scale:\"block(400,400)\")\n            }\n\n          }\n        }\n      }\n    }\n  }\n}\n\nquery Two {\n  guillotine  {\n    getChildren(key:\"/hmdb/persons\" first:5){\n      displayName\n      _path\n  \t}\n\t}\n}\n",
  "variables": null,
  "operationName": "Two"
}
```

It triggers the following error and response:
```json
{
  "status": 500,
  "message": "missing operation name (com.enonic.xp.resource.ResourceProblemException)"
}
```

Part of stack trace: 
```
Caused by: graphql.GraphQLException: missing operation name
	at graphql.execution.ExecutionContextBuilder.build(ExecutionContextBuilder.java:36)
	at graphql.execution.Execution.execute(Execution.java:30)
	at graphql.GraphQL.execute(GraphQL.java:84)
	at graphql.GraphQL.execute(GraphQL.java:61)
	at com.enonic.lib.graphql.GraphQlBean.execute(GraphQlBean.java:258)
	at jdk.nashorn.internal.scripts.Script$Recompilation$378$2576AAA$graphql.L:1#execute(com.enonic.starter.headless:/lib/graphql.js:76)
	at jdk.nashorn.internal.scripts.Script$Recompilation$377$221A$graphql.L:1#post(com.enonic.starter.headless:/services/graphql/graphql.js:8)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:639)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.ScriptObjectMirror.call(ScriptObjectMirror.java:117)
	at com.enonic.xp.script.impl.value.FunctionScriptValue.call(FunctionScriptValue.java:36)
```

I can't pinpoint exactly where the problem lies, as I'm not familiar with Enonic or GraphiQL, but it might be due to the `operationName` from the request not being used when the query is mapped further down to the gql-engine?
Hope this information helps!

**Comment by GlennRicaud** [comment]
This is a syntax issue. Closing the issue
